// Todo el contenido del portafolio vive aquí. Añadir un trabajo = añadir un objeto a PROJECTS.
// pillar: games | web  (decide el color del hilo y la sección). La IA local tiene su propio bloque: AI_BLOCK.
// img: ruta en /img, o null para que se teja una portada a partir del id
// links: { play, live, trailer, repo, itch, lab }

window.PILLARS = [
  { id: 'games', color: 'var(--cochinilla)',
    es: { name: 'Juegos', blurb: 'En Unity y en el navegador. Sistemas que se pueden probar: genética, IA de agentes, combate simultáneo, partidas en red.' },
    en: { name: 'Games', blurb: 'In Unity and in the browser. Systems you can poke at: genetics, agent AI, simultaneous combat, networked matches.' } },
  { id: 'web', color: 'var(--maiz)',
    es: { name: 'Web', blurb: 'Sitios para marcas reales donde el movimiento tiene un motivo: física con el scroll, 3D que vende el producto, fondos que se calculan en la GPU.' },
    en: { name: 'Web', blurb: 'Sites for real brands where motion has a reason: physics on scroll, 3D that sells the product, backgrounds computed on the GPU.' } },
  { id: 'ai', color: 'var(--chilca)', custom: true,
    es: { name: 'IA local' }, en: { name: 'Local AI' } },
];

window.PROJECTS = [
  // ───────────── JUEGOS ─────────────
  { id: 'littlesimworld', pillar: 'games', featured: true, year: '2023',
    img: ['https://cdn.akamai.steamstatic.com/steam/apps/1429880/capsule_616x353.jpg',
          'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1429880/ca71b2e99a91333b909fff49e175f1e35592c343/ss_ca71b2e99a91333b909fff49e175f1e35592c343.1920x1080.jpg'],
    credit: '© .GRAVITY · Steam',
    tags: ['Unity', 'C#', 'Gameplay systems', 'Editor tools'],
    links: { steam: 'https://store.steampowered.com/app/1429880/Little_Sim_World/' },
    es: { title: 'Little Sim World', status: 'Publicado en Steam · contrato de 4 meses',
      text: 'Simulador de vida 2D de Blue Gravity Studios, publicado en Steam. Trabajé cuatro meses como desarrollador Unity contratado por el estudio: sistemas de juego, features y herramientas para el equipo.' },
    en: { title: 'Little Sim World', status: 'Shipped on Steam · 4-month contract',
      text: 'A 2D life sim by Blue Gravity Studios, released on Steam. I spent four months as a contract Unity developer for the studio, working on gameplay systems, features and tools for the team.' } },

  { id: 'morimonchis', pillar: 'games', featured: true, year: '2025–26',
    img: ['morimonchis-huevos', 'morimonchis-arena'],
    video: { loop: 'morimonchis-loop',
      full: { es: 'video/morimonchis-promo.mp4', en: 'video/morimonchis-promo.mp4' } },
    tags: ['Unity 6', 'C#', 'UGS Cloud Save', 'NavMesh', 'ScriptableObjects'],
    links: { repo: 'https://github.com/KurusuDes/RunRunSimulator' },
    es: { title: 'MoriMonchis', status: 'En desarrollo',
      text: 'Criaturas que se crían por genética: cada parte del cuerpo se hereda con sus propias probabilidades. En la arena salen de expedición con IA propia y minan, cazan, hacen de señuelo o huyen según su personalidad.' },
    en: { title: 'MoriMonchis', status: 'In development',
      text: 'Creatures bred through genetics: every body part is inherited with its own odds. In the arena they head out on expeditions with their own AI, mining, hunting, baiting or fleeing depending on personality.' } },

  { id: 'katan', pillar: 'games', featured: true, year: '2026',
    img: ['katan', 'katan-diorama'],
    video: { loop: 'katan-loop',
      full: { es: 'https://kurusudes.github.io/CatanTestFriendos/showcase/katan-x-amiguites-trailer.mp4',
              en: 'https://kurusudes.github.io/CatanTestFriendos/showcase/katan-x-amiguites-trailer-en.mp4' } },
    tags: ['JavaScript', 'Three.js', 'PeerJS · WebRTC', 'Bots'],
    links: { play: 'https://kurusudes.github.io/CatanTestFriendos/',
             repo: 'https://github.com/KurusuDes/CatanTestFriendos' },
    es: { title: 'Katan x Amiguites', status: 'Jugable',
      text: 'Un juego de colonos en el navegador, con editor de mapas, bots, partidas online entre amigos, tablero en 3D y modos que no existen en la caja: a ciegas, con niebla o con eventos.' },
    en: { title: 'Katan x Amiguites', status: 'Playable',
      text: 'A settlers game in the browser, with a map editor, bots, online matches with friends, a 3D board and modes the box never had: blindfold, fog of war, random events.' } },

  { id: 'blobvarium', pillar: 'games', year: '2026', img: 'blobvarium',
    video: { loop: 'blobvarium-loop', fit: 'contain', bg: '#E9DFC8',
      full: { es: 'video/blobvarium-promo-es.mp4', en: 'video/blobvarium-promo-en.mp4' } },
    tags: ['Python', 'NumPy', 'Pillow', 'Supabase', 'Vercel'],
    links: { live: 'https://blobvarium.com' },
    es: { title: 'Blobvarium', status: 'En línea',
      text: 'Cada día nace una criatura inca dibujada al 100 % con código a partir de una semilla, sin IA ni imágenes base. Se gana en una subasta con monedas.' },
    en: { title: 'Blobvarium', status: 'Live',
      text: 'A new Inca creature is born every day, drawn 100% by code from a seed, with no AI and no base images. You win it in a coin auction.' } },

  { id: 'apocalipto', pillar: 'games', year: '2026', img: null, motif: 'tower',
    tags: ['Unity 6 URP', 'Cloud Code', 'Cloud Save', 'Odin'],
    links: {},
    es: { title: 'Torre Viviente', status: 'En desarrollo',
      text: 'Tower defense de una sola torre en tercera persona, donde la torre es el jugador: camina, se ancla a minar yacimientos, resiste oleadas y crece piso a piso con eventos roguelike.' },
    en: { title: 'Living Tower', status: 'In development',
      text: 'A single-tower, third-person tower defense where the tower is you: it walks, anchors to mine deposits, holds off waves and grows floor by floor through roguelike events.' } },

  { id: 'abyss', pillar: 'games', year: '2026', img: null, motif: 'hex',
    tags: ['Unity', 'C#', 'Decoupled sim', 'Tests'],
    links: {},
    es: { title: 'The Abyssal Ledger', status: 'Prototipo',
      text: 'Autobattler táctico de extracción en un campo hexagonal. La simulación de combate vive en su propio ensamblado, separada de Unity y cubierta por tests.' },
    en: { title: 'The Abyssal Ledger', status: 'Prototype',
      text: 'A tactical extraction autobattler on a hex field. The combat simulation lives in its own assembly, decoupled from Unity and covered by tests.' } },

  { id: 'mergekingdoms', pillar: 'games', year: '2026', img: null,
    tags: ['Unity', 'C#', 'EditMode tests'],
    links: {},
    es: { title: 'MergeKingdoms', status: 'En desarrollo',
      text: 'Fusionas bloques para levantar tu reino, pero cada cien años decides si defiendes a tus vecinos de la amenaza o los saqueas mientras están ocupados.' },
    en: { title: 'MergeKingdoms', status: 'In development',
      text: 'You merge blocks to build your kingdom, but every hundred years you choose: defend your neighbours from the threat, or loot them while they’re busy.' } },

  { id: 'hyperinflation', pillar: 'games', year: '2026', img: null,
    tags: ['TypeScript', 'Three.js', 'PeerJS', 'Vite'],
    links: {},
    es: { title: 'Hyper Inflation Coop RPG', status: 'En desarrollo',
      text: 'RPG incremental en el que los números crecen sin freno, para jugar entre amigos en el navegador, conectados punto a punto y sin servidor propio.' },
    en: { title: 'Hyper Inflation Coop RPG', status: 'In development',
      text: 'An incremental RPG where the numbers grow without limit, played with friends in the browser, connected peer to peer with no server of its own.' } },

  { id: 'exponential', pillar: 'games', year: '2026', img: null, motif: 'arrows',
    tags: ['Unity 6 URP', 'C#'],
    links: { repo: 'https://github.com/KurusuDes/ExponentialGrow' },
    es: { title: 'Dungeon Discotec Disaster', status: 'Prototipo',
      text: 'Roguelike por turnos: cada combo de flechas lanza un género musical (rock, salsa, electrónica…) que pega distinto según la raza del enemigo.' },
    en: { title: 'Dungeon Discotec Disaster', status: 'Prototype',
      text: 'Turn-based roguelike: every arrow combo fires a music genre (rock, salsa, electronic…) that hits differently depending on the enemy’s race.' } },

  { id: 'axie', pillar: 'games', year: '2023', img: 'axie',
    tags: ['Unity', 'Game jam'],
    links: { itch: 'https://kurusudes.itch.io/axiedarknessarise' },
    es: { title: 'Axie Darkness Arise', status: '4.º puesto',
      text: 'Hecho en una semana para la Sky Mavis Game Jam 2023, donde quedó cuarto.' },
    en: { title: 'Axie Darkness Arise', status: '4th place',
      text: 'Built in one week for the Sky Mavis Game Jam 2023, where it placed fourth.' } },

  // ───────────── WEB ─────────────
  { id: 'okara', pillar: 'web', year: '2026', img: 'okara',
    tags: ['Next.js', 'Supabase', 'Vercel', 'Virtual advisor'],
    links: { live: 'https://okara.pe' },
    es: { title: 'Okara', status: 'En producción',
      text: 'Rediseño completo de una clínica estética de Lima: mobile-first, con una asesora virtual que atiende y capta pacientes las 24 horas, contenido sincronizado con sus redes y un panel para que el equipo lo gestione solo.' },
    en: { title: 'Okara', status: 'In production',
      text: 'A full redesign for an aesthetic clinic in Lima: mobile-first, with a virtual advisor that answers and captures patients around the clock, content synced from their social accounts and a panel the team runs on its own.' } },

  { id: 'ninawi', pillar: 'web', year: '2026', img: null,
    video: { loop: 'ninawi-loop' },
    tags: ['Matter.js', 'WebGL', 'Vercel'],
    links: { live: 'https://ninawi.com' },
    es: { title: 'Ninawi', status: 'En línea',
      text: 'Web de agencia contada por salas: cada servicio es una gota con física real que se junta, se separa y se transforma mientras haces scroll, sobre un fondo que se calcula en la GPU.' },
    en: { title: 'Ninawi', status: 'Live',
      text: 'An agency site told in rooms: every service is a drop with real physics that merges, splits and transforms as you scroll, over a background computed on the GPU.' } },

  { id: 'recupera', pillar: 'web', year: '2026', img: 'recupera',
    tags: ['HTML/CSS', 'JavaScript', 'Shop'],
    links: { live: 'https://kurusudes.github.io/myautomatedjr-demos/recupera-tricologia/' },
    es: { title: 'Recupera', status: 'Propuesta',
      text: 'Propuesta para un centro de tricología: test gratuito, explicación del diagnóstico capilar con IA, recorrido del tratamiento y tienda, pensada para el móvil.' },
    en: { title: 'Recupera', status: 'Proposal',
      text: 'A proposal for a hair-loss clinic: a free self-test, an explainer for its AI hair diagnosis, the treatment journey and a shop, built for mobile.' } },

  { id: 'lapcustom', pillar: 'web', year: '2026', img: 'lapcustom',
    tags: ['Three.js', 'GSAP', 'HTML/CSS'],
    links: { live: 'https://kurusudes.github.io/LapCustom/', repo: 'https://github.com/KurusuDes/LapCustom' },
    es: { title: 'Lap Custom', status: 'Maqueta',
      text: 'Landing cinematográfica para un taller de tapizado: el auto 3D gira con el scroll, entra al habitáculo y te deja elegir el cuero.' },
    en: { title: 'Lap Custom', status: 'Mockup',
      text: 'A cinematic landing page for an upholstery shop: the 3D car turns as you scroll, moves into the cabin and lets you pick the leather.' } },

  { id: 'avicena', pillar: 'web', year: '2026', img: 'avicena',
    tags: ['HTML/CSS', 'JavaScript', 'AI advisor'],
    links: { live: 'https://kurusudes.github.io/DermatologiaPeru/', repo: 'https://github.com/KurusuDes/DermatologiaPeru' },
    es: { title: 'Avicena', status: 'Propuesta',
      text: 'Propuesta de rediseño para una clínica dermatológica, con un asesor de IA que arma un plan de tratamiento en segundos.' },
    en: { title: 'Avicena', status: 'Proposal',
      text: 'A redesign proposal for a dermatology clinic, with an AI advisor that drafts a treatment plan in seconds.' } },

];

// ───────────── IA LOCAL ─────────────
// Bloque propio: por qué en local, qué se despliega y para qué se usa. Lo que importa es el flujo, no la tarjeta.
window.AI_BLOCK = {
  es: {
    lead: 'Modelos abiertos desplegados en hardware propio. Los datos no salen de la empresa, no hay costo por llamada y los modelos se encadenan en flujos sin límites de cuota.',
    why: [
      ['Privacidad', 'El código, los documentos y el arte del cliente nunca viajan a una API externa.'],
      ['Costo fijo', 'El hardware se paga una vez: mil imágenes o mil respuestas cuestan lo mismo que una.'],
      ['Control', 'Versión del modelo fijada, resultados reproducibles por semilla, nada que cambie de un día para otro.'],
    ],
    stackTitle: 'Qué despliego',
    flowsTitle: 'Cómo se usa',
    hw: 'En la oficina, sobre la plataforma NVIDIA del equipo; en mi estación, sobre una RTX 3090 de 24 GB.',
  },
  en: {
    lead: 'Open models deployed on our own hardware. Data never leaves the company, there are no per-call fees, and models chain into workflows with no quota limits.',
    why: [
      ['Privacy', 'Client code, documents and art never travel to an external API.'],
      ['Fixed cost', 'You pay for the hardware once: a thousand images or answers cost the same as one.'],
      ['Control', 'Pinned model versions, seed-reproducible results, nothing that changes overnight.'],
    ],
    stackTitle: 'What I deploy',
    flowsTitle: 'How it’s used',
    hw: 'At the office, on the team’s NVIDIA platform; at my workstation, on a 24 GB RTX 3090.',
  },
  stack: [
    { es: 'Texto y código', en: 'Text & code', items: ['Qwen3.8', 'Ornith-1.5', 'llama.cpp', 'Ollama', 'Open WebUI'] },
    { es: 'Imagen', en: 'Image', items: ['FLUX.2 klein', 'Z-Image', 'Qwen-Image-Edit', 'ComfyUI'] },
    { es: '3D', en: '3D', items: ['Hunyuan3D 2.1', 'Hi3DGen', 'TRELLIS 2', 'StdGEN', 'Blender'] },
    { es: 'Vídeo', en: 'Video', items: ['Wan 2.2', 'ComfyUI'] },
  ],
  // Cada flujo es un diagrama de nodos: [paso, herramienta, lo que sale hacia el siguiente].
  // Se muestra el pipeline, no el resultado. `proof` es opcional y siempre es un número medido.
  flows: [
    { id: 'asset',
      es: { title: 'De concept a asset de juego', proof: ['1,21 M → 6.000', 'caras → triángulos'],
        text: 'Una imagen generada se convierte en un asset listo para Unity sin una sola herramienta de pago. Cada nodo es un proceso aparte: se puede repetir, medir o cambiar de modelo sin tocar los demás.',
        steps: [['Prompt', 'texto + estilo', 'texto'], ['Concept 2D', 'FLUX.2 klein', 'PNG 1024'],
                ['Recorte', 'limpieza RGBA', 'PNG RGBA'], ['Malla', 'Hi3DGen', '1,2 M caras'],
                ['Textura PBR', 'Hunyuan3D-Paint', 'albedo · rough · metal'],
                ['Curado', 'Blender sin ventana', 'retopo · UV · bake'], ['Asset', 'GLB para Unity', 'LODs + colisionador']] },
      en: { title: 'From concept to game asset', proof: ['1.21 M → 6,000', 'faces → triangles'],
        text: 'A generated image becomes a Unity-ready asset without a single paid tool. Every node is its own process: it can be rerun, measured or swapped for another model without touching the rest.',
        steps: [['Prompt', 'text + style', 'text'], ['2D concept', 'FLUX.2 klein', 'PNG 1024'],
                ['Cutout', 'RGBA cleanup', 'RGBA PNG'], ['Mesh', 'Hi3DGen', '1.2 M faces'],
                ['PBR texture', 'Hunyuan3D-Paint', 'albedo · rough · metal'],
                ['Cleanup', 'headless Blender', 'retopo · UV · bake'], ['Asset', 'GLB for Unity', 'LODs + collider']] } },

    { id: 'agents',
      es: { title: 'Agentes de código privados', proof: ['35 → 59', 'tok/s con predicción multi-token'],
        text: 'El mismo flujo de agente que uso con la nube, apuntado a modelos locales. Sirve para repos que no pueden salir de la oficina: el agente lee, edita y verifica sin enviar una línea fuera.',
        steps: [['Tarea', 'pedido o issue', 'objetivo'], ['Agente', 'Claude Code', 'plan'],
                ['Contexto', 'MCP · repo · editor Unity', 'archivos + escena'],
                ['Modelo', 'llama.cpp · Qwen3.8', 'parche'], ['Verificación', 'tests · capturas', 'informe'],
                ['Entrega', 'commit o PR']] },
      en: { title: 'Private coding agents', proof: ['35 → 59', 'tok/s with multi-token prediction'],
        text: 'The same agent workflow I use with the cloud, pointed at local models. It’s for repos that can’t leave the office: the agent reads, edits and verifies without sending a single line out.',
        steps: [['Task', 'request or issue', 'goal'], ['Agent', 'Claude Code', 'plan'],
                ['Context', 'MCP · repo · Unity editor', 'files + scene'],
                ['Model', 'llama.cpp · Qwen3.8', 'patch'], ['Verification', 'tests · screenshots', 'report'],
                ['Delivery', 'commit or PR']] } },

    { id: 'concepts',
      es: { title: 'Exploración de arte en lote', proof: ['11,2 s', 'por imagen'],
        text: 'Para encontrar la línea de arte de un juego: sujeto fijo, estilo variable y cientos de variantes por sesión, filtradas por cómo se leen en pequeño antes de que las mire una persona.',
        steps: [['Brief', 'sujeto fijo', 'prompt maestro'], ['Variantes', 'estilo variable', 'N prompts'],
                ['Generación', 'Z-Image · FLUX.2 en ComfyUI', 'lote PNG'],
                ['Filtro', 'test de silueta a 32 px', 'finalistas'], ['Curado', 'revisión humana']] },
      en: { title: 'Batch art exploration', proof: ['11.2 s', 'per image'],
        text: 'To find a game’s art direction: fixed subject, varying style and hundreds of variants per session, filtered by how they read at small size before a person ever looks at them.',
        steps: [['Brief', 'fixed subject', 'master prompt'], ['Variants', 'varying style', 'N prompts'],
                ['Generation', 'Z-Image · FLUX.2 in ComfyUI', 'PNG batch'],
                ['Filter', '32 px silhouette test', 'finalists'], ['Curation', 'human review']] } },

    { id: 'video',
      es: { title: 'Vídeo y fondos animados',
        text: 'Clips y fondos en bucle para webs y tráilers. Antes de publicar un vídeo se mide si de verdad aporta: muchas veces un shader de pocos KB hace lo mismo y pesa cien veces menos.',
        steps: [['Entrada', 'imagen o prompt', 'frame'], ['Animación', 'Wan 2.2 en ComfyUI', 'clip'],
                ['Bucle', 'ffmpeg · fundido sin costura', 'MP4'], ['Medición', 'peso frente a un shader', 'veredicto'],
                ['Web', 'fondo o tráiler']] },
      en: { title: 'Video and animated backgrounds',
        text: 'Looping clips and backgrounds for websites and trailers. Before shipping a video I measure whether it’s worth it: often a shader of a few KB does the same at a hundredth of the weight.',
        steps: [['Input', 'image or prompt', 'frame'], ['Animation', 'Wan 2.2 in ComfyUI', 'clip'],
                ['Loop', 'ffmpeg · seamless crossfade', 'MP4'], ['Measure', 'weight vs a shader', 'verdict'],
                ['Web', 'background or trailer']] } },
  ],
};

// Canales de contacto. Los vacíos no se muestran.
window.CONTACT = [
  { label: 'GitHub', href: 'https://github.com/KurusuDes' },
  { label: 'itch.io', href: 'https://kurusudes.itch.io' },
  { label: 'LinkedIn', href: '' },
  { label: 'Email', href: '' },
];

window.UI = {
  es: {
    'nav.games': 'Juegos', 'nav.web': 'Web', 'nav.ai': 'IA local', 'nav.method': 'Método',
    'hero.role': 'Game · Software · AI · Web Developer — Lima, Perú',
    'hero.lead': 'Desarrollador Unity/C# con experiencia en producción comercial, web 3D e IA generativa local. Del prototipo al juego publicado.',
    'hero.cta': 'Ver trabajos',
    'loom.label': 'Tejido nº',
    'loom.note': 'Se teje con código a partir de la fecha de hoy.',
    'loom.again': 'Tejer otro',
    'threads.title': 'Tres hilos',
    'threads.projects': 'trabajos', 'threads.flows': 'flujos',
    'link.play': 'Jugar', 'link.live': 'Ver en vivo', 'link.trailer': 'Tráiler', 'link.repo': 'Código',
    'link.itch': 'itch.io', 'link.steam': 'Ver en Steam', 'link.lab': 'Ver en vivo', 'link.video': 'Ver tráiler', 'player.close': 'Cerrar',
    'card.private': 'Código privado',
    'method.title': 'Cómo trabajo',
    'method.agents.h': 'Con agentes, pero verificando',
    'method.agents.p': 'Desarrollo en Unity junto a Claude Code conectado al editor por MCP: el agente lee la escena, entra en Play y comprueba con capturas lo que cambió. Cada proyecto lleva su documentación viva en Obsidian, con una nota por script (más de 200 en MoriMonchis). Ese método lo empaqueté en un kit para que un proyecto nuevo no empiece de cero.',
    'method.local.h': 'Medir antes de afirmar',
    'method.local.p': 'Antes de elegir un modelo, una herramienta o un parámetro, lo pruebo con un caso real y anoto el número. Así sé qué cabe, cuánto tarda y qué es solo marketing.',
    'method.teach.h': 'Enseñando lo que hago',
    'method.teach.p': 'Enseño desarrollo de videojuegos en Tecsup: programación aplicada a videojuegos y desarrollo multijugador para móviles con Netcode for GameObjects.',
    'footer.title': 'Hablemos',
    'footer.p': '¿Un juego, una web que se mueva o IA que no saque tus datos de la empresa? Escríbeme por cualquiera de estos canales.',
    'footer.made': 'Hecho a mano, sin plantillas. El tejido de arriba cambia cada día.',
  },
  en: {
    'nav.games': 'Games', 'nav.web': 'Web', 'nav.ai': 'Local AI', 'nav.method': 'Method',
    'hero.role': 'Game · Software · AI · Web Developer — Lima, Peru',
    'hero.lead': 'Unity/C# developer with commercial production experience, 3D web and local generative AI. From prototype to shipped game.',
    'hero.cta': 'See the work',
    'loom.label': 'Weave no.',
    'loom.note': 'Woven by code from today’s date.',
    'loom.again': 'Weave another',
    'threads.title': 'Three threads',
    'threads.projects': 'projects', 'threads.flows': 'workflows',
    'link.play': 'Play', 'link.live': 'Live', 'link.trailer': 'Trailer', 'link.repo': 'Code',
    'link.itch': 'itch.io', 'link.steam': 'View on Steam', 'link.lab': 'Live', 'link.video': 'Watch trailer', 'player.close': 'Close',
    'card.private': 'Private code',
    'method.title': 'How I work',
    'method.agents.h': 'With agents, and checking their work',
    'method.agents.p': 'I build in Unity alongside Claude Code wired into the editor through MCP: the agent reads the scene, enters Play mode and verifies changes with screenshots. Every project carries living documentation in Obsidian, one note per script (200+ in MoriMonchis). I packaged that method into a starter kit so new projects don’t start from zero.',
    'method.local.h': 'Measure before claiming',
    'method.local.p': 'Before picking a model, a tool or a setting, I test it on a real case and write down the number. That’s how I know what fits, how long it takes, and what is just marketing.',
    'method.teach.h': 'Teaching what I do',
    'method.teach.p': 'I teach game development at Tecsup: programming applied to games, and mobile multiplayer with Netcode for GameObjects.',
    'footer.title': 'Let’s talk',
    'footer.p': 'A game, a website that moves, or AI that keeps your data in-house? Reach me on any of these.',
    'footer.made': 'Handmade, no templates. The weave up top changes every day.',
  },
};
